# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 152adb128c37f9654ecd0f6890a03e49ddb7a386232122a72cafafcd6d694eda9494fa7de67e17128c102e7ea1cf2b2120b85d058920a1f606bccbdac7ec657a

test:
  secret_key_base: 621ab692442807b7ab531ff21c78a85e27345bbf7dfd538269b13af141856ae56c511c891ec4c930be2abfecfe49ac1f421484ba36c306043489f2dcf5eafcba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
